[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.136.0",
    "langchain>=1.2.15",
    "langchain-community>=0.4.1",
    "langchain-google-genai>=4.2.2",
    "langgraph>=1.1.8",
    "numpy>=2.4.4",
    "pydantic>=2.13.2",
    "python-dotenv>=1.2.2",
    "web3>=7.8.0",
    "tavily-python>=0.7.23",
    "uvicorn>=0.44.0",
]
